Ros2 v0.8.0 pointcloud preprocessor
tier4/AutowareArchitectureProposal.iv pull request #293
Opened 2021-01-25 04:10 UTC by wep21

2021-02-05 01:04 UTC, k0suke-murakami requested changes
Could not build since could not resolve dependency of `autoware_utils` even after #291 is merged
```
In file included from /home/kosuke/autoware_0_8/src/autoware/pilot.auto/sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/vector_map_filter/lanelet2_map_filter_nodelet.cpp:18:
/home/kosuke/autoware_0_8/src/autoware/pilot.auto/sensing/preprocessor/pointcloud/pointcloud_preprocessor/include/pointcloud_preprocessor/vector_map_filter/lanelet2_map_filter_nodelet.hpp:27:10: fatal error: autoware_utils/geometry/boost_geometry.hpp: No such file or directory
   27 | #include "autoware_utils/geometry/boost_geometry.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

2021-02-05 01:04 UTC, k0suke-murakami commented on sensing/preprocessor/pointcloud/pointcloud_preprocessor/package.xml
>    <test_depend>ament_cmake_cppcheck</test_depend>
Need to include `ament_lint_common` like other pakcages? https://github.com/wep21/autoware.iv.universe/blob/9232f7117f8ee0c266e354ceba80feb41ab2137d/system/autoware_state_monitor/package.xml#L32

2021-02-09 12:08 UTC, wep21 commented
@k0suke-murakami ready for review

2021-02-10 00:56 UTC, k0suke-murakami approved these changes

2021-02-10 01:13 UTC, k0suke-murakami commented
- [x]  Build passed

- [x] ros2 run success.
 Node : pointcloud_accumulator_node, concatenate_data_node, ray_ground_filter_node, crop_box_filter_node, ring_outlier_filter_node, distance_based_compare_map_filter_node , voxel_based_approximate_compare_map_filter_node ,downsample_filter_node, voxel_based_compare_map_filter_node, passthrough_filter_node , voxel_distance_based_compare_map_filter_node, passthrough_filter_uint16_node  ,voxel_grid_outlier_filter_node
- [x] Test  passed

2021-02-10 01:13 UTC, merged