port part of external_cmd_selector
tier4/AutowareArchitectureProposal.iv pull request #497
Opened 2021-11-04 09:26 UTC by k0suke-murakami

Signed-off-by: kosuke murakami <kosuke.murakami@tier4.jp>

## Description

- [ ]  autoware_control_msgs::srv::ExternalCommandSelect
- [ ]  autoware_control_msgs::msg::ExternalCommandSelectorMode
- [x]  autoware_vehicle_msgs::msg::ShiftStamped
- [ ]  autoware_vehicle_msgs::msg::TurnSignal, lasck of `hazard`
- [ ]  autoware_external_api_msgs::msg::Heartbeat,
- [ ]  autoware_external_api_msgs::msg::ControlCommandStamped,
- [ ]  autoware_external_api_msgs::msg::GearShiftStamped,
- [ ]  autoware_external_api_msgs::msg::TurnSignalStamped,
- [ ]  autoware_external_api_msgs::msg::Heartbeat,

## Review Procedure

## Remarks

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [pull request guidelines][pull-request-guidelines]
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

2021-11-10 07:41 UTC, TakaHoribe approved these changes

2021-11-10 07:47 UTC, isamu-takagi requested changes

2021-11-10 07:47 UTC, isamu-takagi commented on control/external_cmd_selector/src/external_cmd_selector/external_cmd_selector_node.cpp
> +  message.command = command.gear_shift.data;
定数の割り当てが異なり、代入だと対応が取れないのでこれの逆変換を行う必要があると思います。
https://github.com/tier4/autoware_iv_msgs/blob/use-autoware-auto-msgs/autoware_iv_auto_msgs_converter/include/autoware_iv_auto_msgs_converter/autoware_iv_auto_msgs_converter.hpp#L147-L189

2021-11-10 07:53 UTC, k0suke-murakami commented on control/external_cmd_selector/src/external_cmd_selector/external_cmd_selector_node.cpp
> +  message.command = command.gear_shift.data;
@isamu-takagi 
これはそもそも変換元のmsg（`ExternalGearShift`）がautoに対応していないことに起因しており、根本的にはそちらの解決をしていくという方針なのでしょうか？
（個人としては逆変換は暫定対応と感じており、根本対応を進めた方がいいのではと思っています。このあたり方針は把握しきれておらず）

2021-11-10 07:56 UTC, isamu-takagi commented
また、autoware_vehicle_msgs::msg::TurnSignal は TurnIndicatorsCommand と HazardLightsCommand に分割することになっていたと思います。（vehicle_cmd_gate 側でも対応が必要ですね……。）

2021-11-10 07:58 UTC, k0suke-murakami commented
` autoware_vehicle_msgs::msg::TurnSignal`　は現在auto側でhazardの情報がないため、互換性がないと判断しポーティングをskipしています。
堀部さんから現在互換性のあるものだけ一旦移して欲しい、と言われているためこのようなPRになっています。

2021-11-10 08:02 UTC, isamu-takagi commented on control/external_cmd_selector/src/external_cmd_selector/external_cmd_selector_node.cpp
> +  message.command = command.gear_shift.data;
External系(autoware_api_msgs)はFMSが使っているので一定期間メッセージ型を維持する必要があり、FMSでのAPIバージョンによるメッセージ型の切り替え処理が入るまでは変換を行わないといけないです。

2021-11-11 08:00 UTC, taikitanaka3 commented
@k0suke-murakami 
can you Re force push again? I accidentally push to `external command selector` commit not `external command converter`

2021-11-11 08:26 UTC, k0suke-murakami commented on control/external_cmd_selector/src/external_cmd_selector/external_cmd_selector_node.cpp
> +  message.command = command.gear_shift.data;
@isamu-takagi 
こちら逆変換のprをこちらに出しました https://github.com/tier4/autoware_iv_msgs/pull/64

2021-11-11 23:46 UTC, isamu-takagi approved these changes

2021-11-12 07:39 UTC, tkimura4 commented on control/external_cmd_selector/include/external_cmd_selector/external_cmd_selector_node.hpp
> +#include <autoware_auto_vehicle_msgs/msg/turn_indicators_command.hpp>
Could you sort?

>  #include <autoware_auto_vehicle_msgs/msg/gear_command.hpp>
-#include <autoware_auto_vehicle_msgs/msg/turn_indicators_command.hpp>
 #include <autoware_auto_vehicle_msgs/msg/hazard_lights_command.hpp>
+#include <autoware_auto_vehicle_msgs/msg/turn_indicators_command.hpp>
 #include <autoware_control_msgs/msg/external_command_selector_mode.hpp>
 #include <autoware_control_msgs/srv/external_command_select.hpp>
 #include <autoware_external_api_msgs/msg/control_command_stamped.hpp>

2021-11-12 07:47 UTC, tkimura4 commented
Build and test for PR:
depends on https://github.com/tier4/AutowareArchitectureProposal_msgs/pull/7

2021-11-12 09:42 UTC, tkimura4 commented on control/external_cmd_selector/include/external_cmd_selector/external_cmd_selector_node.hpp
> +#include <autoware_auto_vehicle_msgs/msg/hazard_lights_command.hpp>
```suggestion
#include <autoware_auto_vehicle_msgs/msg/gear_command.hpp>
#include <autoware_auto_vehicle_msgs/msg/hazard_lights_command.hpp>
#include <autoware_auto_vehicle_msgs/msg/turn_indicators_command.hpp>
```

2021-11-12 10:02 UTC, merged