support autoware auto msgs
tier4/AutowareArchitectureProposal.iv pull request #504
Opened 2021-11-05 00:59 UTC by taichiH

## Description
port traffic light classifier

## Review Procedure

## Remarks

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [pull request guidelines][pull-request-guidelines]
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

2021-11-05 02:12 UTC, kmiya requested changes

2021-11-05 02:12 UTC, kmiya commented on perception/traffic_light_recognition/traffic_light_classifier/include/traffic_light_classifier/nodelet.hpp
> +    trafic_signal_array_pub_;
```suggestion
    traffic_signal_array_pub_;
```
Nit: Detected as typo. Please check the other warnings.

2021-11-05 03:38 UTC, kmiya commented on perception/traffic_light_recognition/traffic_light_classifier/include/traffic_light_classifier/nodelet.hpp
> +    trafic_signal_array_pub_;
Fixed in 1509931.

2021-11-08 05:00 UTC, yukkysaito approved these changes

2021-11-09 01:21 UTC, taichiH commented
@kmiya Approveお願いできないでしょうか？

2021-11-09 02:03 UTC, kmiya approved these changes
@taichiH お待たせしました :bow:

2021-11-10 01:01 UTC, merged