port lidar_centerpoint
tier4/AutowareArchitectureProposal.iv pull request #527
Opened 2021-11-08 00:45 UTC by yukke42

## Description

.auto porting

I checked that the objects are published.

## Review Procedure

## Remarks

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [pull request guidelines][pull-request-guidelines]
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

2021-11-09 08:46 UTC, yukkysaito approved these changes

2021-11-09 08:47 UTC, yukkysaito requested changes

2021-11-09 08:47 UTC, yukkysaito commented on perception/object_recognition/detection/lidar_centerpoint/src/node.cpp
> +    obj.existence_probability = score;
コメントで
// TODO 確率ではないが一時的な処置であり、scoreはclassificationのsoftmaxの結果
みたいな記述を入れたほうがいいかもす

2021-11-10 07:40 UTC, yukkysaito commented on perception/object_recognition/detection/lidar_centerpoint/src/node.cpp
> +    obj.existence_probability = score;
一応TODOであくまでもDNNで推定しているのはconfidenceであり、確率ではないという文言を入れてもらえますか？
readmeにもあるといいかもです

2021-11-10 10:04 UTC, yukke42 commented on perception/object_recognition/detection/lidar_centerpoint/src/node.cpp
> +    obj.existence_probability = score;
fixed at [a65da99](https://github.com/tier4/AutowareArchitectureProposal.iv/pull/527/commits/a65da99b0df6b5568dc69be5b09b2b9315811ec3)

2021-11-10 10:06 UTC, yukke42 commented on perception/object_recognition/detection/lidar_centerpoint/src/node.cpp
> +    obj.existence_probability = score;
fixed at [61be94e](https://github.com/tier4/AutowareArchitectureProposal.iv/pull/527/commits/61be94eb61f4f3344ce3927a7b7a6d14311b464f)

2021-11-10 10:15 UTC, yukkysaito approved these changes

2021-11-10 10:16 UTC, merged